spring:
  datasource:
    druid:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:qtrade_ai
      username:
      password:
    schema: classpath:h2/schema.sql
    data: classpath:h2/data.sql